<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var array<int,string>    $chart_options
 * @var int                  $chartOption
 * @var array<int,string>    $tab_options
 * @var int                  $tabOption
 * @var array<int,string>    $xtR_options
 * @var int                  $xtROption
 * @var string               $title
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), route(ModulesAllPage::class) => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>
<p>
    <?= I18N::translate('Options for starting XTV - primary view') ?>
</p>

<form method="post">
    <div class="row mb-3">
        <legend class="col-form-label col-sm-5"  for="chartOption">
            <?= /* I18N: Configuration option */
            I18N::translate("XTV in Genealogy/Charts - start as ...") ?>
        </legend>
        <div class="col-sm-7">
            <?= view('components/radios', ['name' => 'chartOption', 'selected' => $chartOption, 'options' => $chart_options]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <legend class="col-form-label col-sm-5"  for="dumpOption">
            <?= /* I18N: Configuration option */
            I18N::translate("XTV in Genealogy/Charts - dump HTML to file") ?>
        </legend>
        <div class="col-sm-7">
            <?= view('components/radios', ['name' => 'dumpOption', 'selected' => $dumpOption, 'options' => $dump_options]) ?>
        </div>
    </div>

    <fieldset class="row mb-3">
        <legend class="col-form-label col-sm-5" for="tabOption">
            <?= /* I18N: Configuration option */
            I18N::translate("XTV in Individual page/Tabs - start as ...") ?>
        </legend>
        <div class="col-sm-7">
            <?= view('components/radios', ['name' => 'tabOption', 'selected' => $tabOption, 'options' => $tab_options]) ?>
        </div>

    </fieldset>

    <fieldset class="row mb-3">
        <legend class="col-form-label col-sm-5" for="tabOption">
            <?= /* I18N: Configuration option */
            I18N::translate("XTV as Relationship Viewer (choose a 2nd person with options)") ?>
        </legend>
        <div class="col-sm-7">
            <?= view('components/radios', ['name' => 'xtROption', 'selected' => $xtROption, 'options' => $xtR_options]) ?>
        </div>

    </fieldset>

    <div class="row mb-3">
        <div class="offset-sm-5 col-sm-7">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>

    <?= csrf_field() ?>
</form>
