<?php

/**
 * webtrees - clippings cart enhanced
 *
 * Copyright (C) 2025 huhwt. All rights reserved.
 *
 */

use Fisharebest\Webtrees\I18N;

?>

<div class="input-group">
    <button id="btn_Filter" class="btn btn-secondary cce-btn" type="button" title="<?= I18N::translate('Filter') ?>">
        <span class="wt-icon-filter">
            <svg class="fa-solid fa-filter fa-fw cce-fw" aria-hidden="true" focusable="false" data-prefix="far" data-icon="filter" role="img" viewBox="0 0 512 512" height="24px" xmlns="http://www.w3.org/2000/svg" data-fa-i2svg="">
                <path fill="currentcolor" d="m3.9,54.9c6.6,-14 20.6,-22.9 36.1,-22.9l432,0c15.5,0 29.5,8.9 36.1,22.9s4.6,30.5 -5.2,42.5l-182.9,223.5l0,127.1c0,12.1 -6.8,23.2 -17.7,28.6s-23.8,4.3 -33.5,-3l-64,-48c-8.1,-6 -12.8,-15.5 -12.8,-25.6l0,-79.1l-183,-223.6c-9.7,-11.9 -11.8,-28.5 -5.1,-42.4z"/>
            </svg>
        </span>
    </button>
</div>
<?php
