<?php

namespace HuHwt\WebtreesMods\InteractiveTreeXT;

// use HuHwt\WebtreesMods\InteractiveTreeXT\Module\TreeViewXTmod;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree        $tree
 * @var string      $XREFroot
 * @var string      $innerHTML
 * @var string      $name
 * @var bool        $isChart
 * @var string      $module
 * @var bool        $withCCE
 * @var string      $markdeceased
 * @var string      $showseparated
 * @var string      $bfsTitle
 * @var string      $pmaphide
 */

    $classCCEadapter = 'noCCEadapter';              // there is no CCE instance active ...      -> display: none
    $urlCCEadapter = '';                            // ... so is no need to define a data-definition
    if ($withCCE) {
        $classCCEadapter = 'tvbclipping';
        $urlCCEadapter = 'data-url-Cceadapter="' . e(route(InteractiveTreeXTmod::class, ['module' => $module, 'action' => 'CCEadapter', 'tree' => $tree->name(), 'XREFindi' => $XREFroot])) . '"';
    }

    $urlDetails = 'data-url-details="' . e(route(InteractiveTreeXTmod::class, ['module' => $module, 'action' => 'Details', 'tree' => $tree->name(), 'XREFroot' => $XREFroot])) . '"';

    $urlIndividuals = 'data-url-individuals="' . e(route(InteractiveTreeXTmod::class, ['module' => $module, 'action' => 'Individuals', 'tree' => $tree->name(), 'XREFroot' => $XREFroot, 'showseparated' => $showseparated])) . '"';

    $cl_Pmap        = $pmaphide == '0' ? ' class="not-visible"' : '';

    $tvbpm_pressed  = $pmaphide == '0' ? '' : ' tvPressed';

    $tools_ul1      = $markdeceased ? 'ul1-10' : 'ul1-09';

?>

<div class="wt-chart wt-chart-interactive">
    <div id="<?= $name ?>_out" class="tv_out xtv_out"  <?= $urlDetails ?>  <?= $urlIndividuals ?>  <?= $urlCCEadapter ?> style="height: 300px">
        <div id="<?= $name ?>_tools" class="tv_tools">
            <ul class="<?= $tools_ul1 ?>">
                <li id="<?= $name ?>bCompact" class="tv_button tvbcompact" title="<?= I18N::translate('Use compact layout') ?>">
                </li>
                <li id="<?= $name ?>bShowNext" class="tv_button tvbshownext tvPressed" title="<?= I18N::translate('Expand next links') ?>">
                </li>
                <li id="<?= $name ?>bShowStats" class="tv_button tvbshowstats" title="<?= I18N::translate('Current state') ?>">
                </li>
                <li id="<?= $name ?>bNlistID" class="tv_button tvbnamelist" title="<?= I18N::translate('Show name list') ?>">
                </li>
                <li id="<?= $name ?>bPageMap" class="tv_button tvbpagemap-tr<?= $tvbpm_pressed ?>" title="<?= I18N::translate('Show pagemap') ?>">
                </li>
                <li id="<?= $name ?>bfs" class="tv_button tvfs-switch-expand-screen" title="<?= $bfsTitle ?>">
                </li>
                <li id="tvbFullscreen" class="tv_button">
                    <a href="#" data-wt-fullscreen=".wt-chart-interactive">
                        <span title="<?= I18N::translate('Enter fullscreen') ?>"><?= view('icons/enter-fullscreen') ?></span>
                        <span title="<?= I18N::translate('Exit fullscreen') ?>"><?= view('icons/exit-fullscreen') ?></span>
                    </a>
                </li>
                <li id="<?= $name ?>bexportPNG" class="tv_button tvbexportpng" title="<?= I18N::translate('Export to PNG') ?>">
                </li>
                <?php if ($markdeceased): ?>
                    <li id="<?= $name ?>bHideDeceased" class="tv_button tvbhidedeceased" title="<?= I18N::translate('Hide/show deceased individuals') ?>">
                    </li>
                <?php endif ?>
                <li id="<?= $name ?>bClipping" class="tv_button <?= $classCCEadapter ?>" title="<?= I18N::translate('Add this records to the clippings cart') ?>">
                </li>
                <li id="<?= $name ?>_loading" class="tv_button">
                    <i class="icon-loading-small"></i>
                </li>
            </ul> <!--
            <ul class="ul2">
                <li id="< ?= $name ?>bCenter" class="tv_center tv_button tvbcenter" title="< ?=I18N::translate('Center on root')?>">
                </li>
            </ul> -->
        </div>
        <div id="<?= $name ?>_shownext" class="tv_shownext">
            <ul>
                <li id="<?= $name ?>bShowNext1" class="tv_button tvbshownext1" title="<?=I18N::translate('+1 Level')?>">
                </li>
                <li id="<?= $name ?>bShowNextAll" class="tv_button tvbshownextAll" title="<?=I18N::translate('Show all')?>">
                </li>
            </ul>
        </div>
        <div id="<?= $name ?>_showstats" class="tv_showstats">
            <div>
                <div id="<?= $name ?>sNames" class="tv_showstats_li"><div><?= I18N::translate('Names in view') ?></div><div>0</div>
                </div>
                <div id="<?= $name ?>sLinks" class="tv_showstats_li"><div><?= I18N::translate('Links in view') ?></div><div>0</div>
                </div>
                <div id="<?= $name ?>sStates" class="tv_showstats_li"><div><?= I18N::translate('Generations in view') ?></div>&nbsp;<div>0</div><?= I18N::translate('till') ?><div>0</div>
                </div>
                <div id="<?= $name ?>sDims" class="tv_showstats_li"><div><?= I18N::translate('Chart dimensions') ?></div><div><?= I18N::translate('Width:') ?></div><div>0</div><div><?= I18N::translate('Height:') ?></div><div>0</div>
                </div>
                <div id="<?= $name ?>sGenStats" class="tv_showstats_tab" title="<?= I18N::translate('Individuals in generations') ?>" dtitle="<?= I18N::translate('Click here to toggle highlighting') ?>">
                </div>
            </div>
        </div>
        <div id="<?= $name ?>_NlistID" class="tv_namelistID">
            <div id="<?= $name ?>_NlistIDheader" class="tv_namelistheader">
                <div><?= I18N::translate('Click here to move')?></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistIDSave" class="huhwt_save bdownload_save_txt huhwt_button" title="<?= I18N::translate('Download as textfile') ?>"></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistIDClose" class="huhwt_close bClose huhwt_button" title="<?= I18N::translate('close')?>"></div>
            </div>
            <p id="<?= $name ?>lNames" > <span><?= I18N::translate('Names in view') ?></span> <span>0</span>
            </p>
            <p id="<?= $name ?>lLinks" > <span><?= I18N::translate('Links in view') ?></span> <span>0</span>
            </p>
            <ul id="<?= $name ?>_NlistIDul" class="tv_namelistul" title="<?= I18N::translate('Click here to toggle highlighting') ?>">
            </ul>
        </div>
        <div id="<?= $name ?>_NlistGL" class="tv_namelistGL">
            <div id="<?= $name ?>_NlistGLheader" class="tv_namelistheader">
                <div><?= I18N::translate('Click here to move')?></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistGLClose" class="huhwt_close bClose huhwt_button" title="<?= I18N::translate('close')?>"></div>
            </div>
            <p id="<?= $name ?>glNames" > <span><?= I18N::translate('Names in view') ?></span> <span>0</span>
            </p>
            <p id="<?= $name ?>glGen" > <span><?= I18N::translate('Generation:') ?></span> <span>_</span>
            </p>
            <ul id="<?= $name ?>_NlistGLul" class="tv_namelistul" title="<?= I18N::translate('Click here to toggle highlighting') ?>">
            </ul>
        </div>
        <div id="<?= $name ?>_in" class="xtv_in" dir="ltr">
            <?= $innerHTML ?>
        </div>
        <canvas id="page-map"<?= $cl_Pmap ?> ></canvas>
        </div>
</div>
<script>
        pagemap(document.querySelector('#page-map'), {
            viewport: document.querySelector('.xtv_in'),
            interval: 100,
        });
</script>