<?php

namespace HuHwt\WebtreesMods\InteractiveTreeXT;

// use HuHwt\WebtreesMods\InteractiveTreeXT\Module\TreeViewXTmod;

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;

/**
 * @var Tree        $tree
 * @var string      $XREFroot
 * @var string      $innerHTML
 * @var string      $name
 * @var bool        $isChart
 * @var string      $module
 * @var bool        $withCCE
 * @var string      $markdeceased
 * @var string      $showseparated
 * @var string      $bseTitle
 * @var string      $minTitle
 * @var string      $maxTitle
 * @var string      $pmaphide
 * @var bool        $xtRmode
 * @var bool        $doExpand
 * @var string      $xtv_in
 */

    $classCCEadapter= 'noCCEadapter';           // when there is no CCE instance active ...      -> display: none
    $urlCCEadapter  = '';                           // ... so is no need to define a data-definition ...
    $ul1_cnt        = 8;                            // ... and we have to handle only 8 controls
    if ($withCCE) {                             // we have an active CCE instance ...
        $classCCEadapter = 'tvbclipping';           // ... so set the button-image --- and the data-definition
        $urlCCEadapter = 'data-url-Cceadapter="' . e(route(InteractiveTreeXTmod::class, ['module' => $module, 'action' => 'CCEadapter', 'tree' => $tree->name(), 'XREFindi' => $XREFroot])) . '"';
        $ul1_cnt++;                                 // ... and use 1 more control
    }

    $urlDetails = 'data-url-details="' . e(route(InteractiveTreeXTmod::class, ['module' => $module, 'action' => 'Details', 'tree' => $tree->name(), 'XREFroot' => $XREFroot])) . '"';

    $urlIndividuals = 'data-url-individuals="' . e(route(InteractiveTreeXTmod::class, ['module' => $module, 'action' => 'Individuals', 'tree' => $tree->name(), 'XREFroot' => $XREFroot, 'showseparated' => $showseparated])) . '"';

    $cl_Pmap        = $pmaphide == '0' ? ' class="page-map not-visible"' : ' class="page-map"';   // the pagemap shall not be showed ...

    $tvbpm_pressed  = $pmaphide == '0' ? '' : ' tvPressed';             // ... so the correspondig button will not be shown pressed

    if ($markdeceased) {                        // we are interested to diff deceased from already (to be) living persons ...
        $ul1_cnt++;                             // ... and use 1 more control
    }

    $tools_ul1      = $ul1_cnt < 10 ? 'ul1-0' . (string) $ul1_cnt : 'ul1-' . (string) $ul1_cnt;

?>

<div class="wt-chart wt-chart-interactive">
    <div id="<?= $name ?>_out" class="tv_out xtv_out"  <?= $urlDetails ?>  <?= $urlIndividuals ?>  <?= $urlCCEadapter ?> style="height: 300px">
        <div id="<?= $name ?>_tools" class="tv_tools">
            <ul class="<?= $tools_ul1 ?>">
                <li id="<?= $name ?>bCompact" class="tv_button tvbcompact" title="<?= I18N::translate('Use compact layout') ?>">
                </li>
                <li id="<?= $name ?>bShowNext" class="tv_button tvbshownext tvPressed" title="<?= I18N::translate('Expand next links') ?>">
                </li>
                <li id="<?= $name ?>bShowStats" class="tv_button tvbshowstats" title="<?= I18N::translate('Current state') ?>">
                </li>
                <li id="<?= $name ?>bNlistID" class="tv_button tvbnamelist" title="<?= I18N::translate('Show name list') ?>">
                </li>
                <li id="<?= $name ?>bPageMap" class="tv_button tvbpagemap-tr<?= $tvbpm_pressed ?>" title="<?= I18N::translate('Show pagemap') ?>">
                </li>
                <li id="<?= $name ?>bse" class="tv_button tvfs-switch-expand-screen" title="<?= $bseTitle ?>">
                </li>
                <li id="tvbFullscreen" class="tv_button">
                    <a href="#" data-wt-fullscreen=".wt-chart-interactive">
                        <span title="<?= I18N::translate('Enter fullscreen') ?>"><?= view('icons/enter-fullscreen') ?></span>
                        <span title="<?= I18N::translate('Exit fullscreen') ?>"><?= view('icons/exit-fullscreen') ?></span>
                    </a>
                </li>
                <li id="<?= $name ?>bexportPNG" class="tv_button tvbexportpng" title="<?= I18N::translate('Export to PNG') ?>">
                </li>
                <?php if ($markdeceased): ?>
                    <li id="<?= $name ?>bHideDeceased" class="tv_button tvbhidedeceased" title="<?= I18N::translate('Hide/show deceased individuals') ?>">
                    </li>
                <?php endif ?>
                <li id="<?= $name ?>bClipping" class="tv_button <?= $classCCEadapter ?>" title="<?= I18N::translate('Add this records to the clippings cart') ?>">
                </li>
                <li id="<?= $name ?>_loading" class="tv_button">
                    <i class="icon-loading-small"></i>
                </li>
            </ul> <!--
            <ul class="ul2">
                <li id="< ?= $name ?>bCenter" class="tv_center tv_button tvbcenter" title="< ?=I18N::translate('Center on root')?>">
                </li>
            </ul> -->
        </div>
        <div id="<?= $name ?>_shownext" class="tv_shownext">
            <ul>
                <li id="<?= $name ?>bShowNext1" class="tv_button tvbshownext1" title="<?=I18N::translate('+1 Level')?>">
                </li>
                <li id="<?= $name ?>bShowNextAll" class="tv_button tvbshownextAll" title="<?=I18N::translate('Show all')?>">
                </li>
            </ul>
        </div>
        <div id="<?= $name ?>_showstats" class="tv_showstats">
            <div>
                <div id="<?= $name ?>sNames" class="tv_showstats_li"><div><?= I18N::translate('Names in view') ?></div><div>0</div>
                </div>
                <div id="<?= $name ?>sLinks" class="tv_showstats_li"><div><?= I18N::translate('Links in view') ?></div><div>0</div>
                </div>
                <div id="<?= $name ?>sStates" class="tv_showstats_li"><div><?= I18N::translate('Generations in view') ?></div>&nbsp;<div>0</div><?= I18N::translate('till') ?><div>0</div>
                </div>
                <div id="<?= $name ?>sDims" class="tv_showstats_li"><div><?= I18N::translate('Chart dimensions') ?></div><div><?= I18N::translate('Width:') ?></div><div>0</div><div><?= I18N::translate('Height:') ?></div><div>0</div>
                </div>
                <div id="<?= $name ?>sGenStats" class="tv_showstats_tab" title="<?= I18N::translate('Individuals in generations') ?>" dtitle="<?= I18N::translate('Click here to toggle highlighting') ?>">
                </div>
            </div>
        </div>
        <div id="<?= $name ?>_NlistID" class="tv_namelistID">
            <div id="<?= $name ?>_NlistIDheader" class="tv_namelistheader">
                <div><?= I18N::translate('Click here to move')?></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistIDFilter" class="huhwt_button tv_filter" title="<?= I18N::translate('Filter name list') ?>"></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistIDSave" class="huhwt_save bdownload_save_txt huhwt_button" title="<?= I18N::translate('Download as textfile') ?>"></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistIDClose" class="huhwt_close bClose huhwt_button" title="<?= I18N::translate('close')?>"></div>
            </div>
            <div id="<?= $name ?>_NlistID_info">
                <p id="<?= $name ?>lNames" > <span><?= I18N::translate('Names in view') ?></span> <span>0</span>
                </p>
                <p id="<?= $name ?>lLinks" > <span><?= I18N::translate('Links in view') ?></span> <span>0</span>
                </p>
            </div>
            <div id="<?= $name ?>_NlistID_filter" class="tv_namelistfilter hidden" >
                <input type="search" placeholder="<?= I18N::translate('Type here to filter the list')?>" oninput="NlistID_filterByName(event, '<?= $name ?>')">
                <p id="<?= $name ?>lNames_filter" > <span><?= I18N::translate('Names in view') ?></span> <span>0</span>
                </p>
            </div>
            <ul id="<?= $name ?>_NlistIDul" class="tv_namelistul" title="<?= I18N::translate('Click here to toggle highlighting') ?>">
            </ul>
        </div>
        <div id="<?= $name ?>_NlistGL" class="tv_namelistGL">
            <div id="<?= $name ?>_NlistGLheader" class="tv_namelistheader">
                <div><?= I18N::translate('Click here to move')?></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistGLFilter" class="huhwt_button tv_filter" title="<?= I18N::translate('Filter name list') ?>"></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div class="huhwt_button_tr"></div>
                <div id="<?= $name ?>_NlistGLClose" class="huhwt_close bClose huhwt_button" title="<?= I18N::translate('close')?>"></div>
            </div>
            <div id="<?= $name ?>_NlistGL_info">
                <p id="<?= $name ?>glNames" > <span><?= I18N::translate('Names in view') ?></span> <span>0</span>
                </p>
                <p id="<?= $name ?>glGen" > <span><?= I18N::translate('Generation:') ?></span> <span>_</span>
                </p>
            </div>
            <div id="<?= $name ?>_NlistGL_filter" class="tv_namelistfilter hidden" >
                <input type="search" placeholder="<?= I18N::translate('Type here to filter the list')?>" oninput="NlistGL_filterByName(event, '<?= $name ?>')">
                <p id="<?= $name ?>glNames_filter" > <span><?= I18N::translate('Names in view') ?></span> <span>0</span>
                </p>
            </div>
            <ul id="<?= $name ?>_NlistGLul" class="tv_namelistul" title="<?= I18N::translate('Click here to toggle highlighting') ?>">
            </ul>
        </div>
        <div id="<?= $name ?>_in" class="xtv_in_xtr <?= $xtv_in ?>" dir="ltr">
            <?= $innerHTML ?>
        </div>
        <canvas id="page-map<?= $name ?>"<?= $cl_Pmap ?> ></canvas>
        </div>
</div>
  
<script>
    pagemap(document.querySelector('#page-map<?= $name ?>'), {
        viewport: document.querySelector('#' + '<?= $name ?>' + '_in.xtv_in_xtr'),
        interval: 100,
    });
</script>