<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use HuHwt\WebtreesMods\InteractiveTreeXT\Configuration;

/**
 * @var array         $individuals - [0] first individual, [1] second individual, ... up to [4]
 * @var object        $individual2
 * @var int           $showmatri
 * @var int           $showimplex
 * @var int           $suppimplex
 * @var int           $markdeceased
 * @var int           $showseparated
 * @var int           $generations
 * @var bool          $do_VER
 * @var array         $htmls - [0] first treeview, [1] second treeview, ... up to [4]
 * @var array         $jss   - [0] first treeview, [1] second treeview, ... up to [4]
 * @var string        $module   - this module's name
 * @var string        $title
 * @var string        $ctitle
 * @var array         $subtitles - [0] first treeview, [1] second treeview, ... up to [4]
 * @var array|string  $xtStruct
 * @var array|string  $verData
 * @var int           $vER_find
 * @var array|string  $vERfunctions
 */

    $label_VER = '(' . I18N::translate('Individual') . ' 2 -> ' . I18N::translate('Relations view') . ')';

    $individual = $individuals[0];

    $show_path  = false;        // [EW.H] - debug option -> true: the processed path will be shown in html
?>

<h3 class="wt-page-title">
    <?= $ptitle ?>
</h3>

<form method="post" class="wt-page-options wt-page-options-compact-chart d-print-none">
    <?= csrf_field() ?>

    <div class="row form-group">
        <label class="col-sm-1-10 col-form-label wt-page-options-label" for="xref">
            <?= I18N::translate('Individual') ?>
        </label>
        <div class="col-sm-10 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'xref', 'individual' => $individual, 'tree' => $individual->tree(), 'required' => true]) ?>
        </div>
    </div>
    <?php if ($do_VER) : ?>
        <div class="row form-group">
            <label class="col-sm-1-10 col-form-label wt-page-options-label" for="xref">
                <?= $label_VER ?>
            </label>
            <div class="col-sm-10 wt-page-options-value">
                <?= view('components/select-individual', ['name' => 'xref2', 'individual' => $individual2, 'tree' => $individual->tree(), 'required' => false]) ?>
            </div>
        </div>
        <div class="row form-group">
            <label class="col-sm-1-10 col-form-label wt-page-options-label">
                &nbsp;
            </label>
            <div class="col-sm-10 wt-page-options-value">
                <?= view('components/radios-inline', ['name' => 'find', 'selected' => $vER_find, 'options' => $vERfunctions]) ?>
            </div>
        </div>
    <?php endif ?>

    <div class="row form-group" id="XToptions">
        <div class="col-sm-1-10 wt-page-options-label"></div>
        <div class="col-sm-1 wt-page-options-value">
            <input class="btn btn-primary" type="submit" value="<?= I18N::translate('view') ?>">
        </div>
        <div class="col-sm-1-10 wt-page-options-value pt-2" id="shownext">
            <?php $label_sm = I18N::translate('Maternal side takes precedence') . '&nbsp;&nbsp;' ?>
            <?=
                view('components/checkbox', [
                'name' => 'showmatri', 'id' => 'cb_smatri', 'value' => $showmatri, 'checked' => ($showmatri > 0), 'label' => $label_sm ])
            ?>
        </div>
        <div class="col-sm-3-20 huhwt_buttongroup pt-2">
            <span> <?= I18N::translate('Generations in first view') ?> &nbsp;&nbsp; </span>
            <div id="showgens" class="huhwt_buttongroup">
                <div class="huhwt_button"><i id="showgensSub" class="bMinus huhwt_button" title="<?= I18N::translate('Decrement') ?>"></i></div>
                <input
                    class="form-control"
                    id="generations"
                    name="generations"
                    min="<?=Configuration::MIN_GENERATIONS ?>"
                    max="<?=Configuration::MAX_GENERATIONS ?>"
                    step="0"
                    readonly="true"
                    type="number"
                    value="<?= e($generations) ?>"
                >
                <div class="huhwt_button"><i id="showgensAdd" class="bPlus huhwt_button" title="<?= I18N::translate('Increment') ?>"></i></div>
            </div>
        </div>
        <div class="col-sm-1-10 wt-page-options-value pt-2" id="showimplex" title="<?= I18N::translate('Checked -> Implex-affected relations will be explicitly marked') ?>">
            <?php $label_swi = I18N::translate('Show Implex'); ?>
            <?=
                view('components/checkbox', [
                'name' => 'showimplex', 'id' => 'cb_swimplex', 'value' => $showimplex, 'checked' => ($showimplex > 0), 'label' => $label_swi ])
            ?>
        </div>
        <div class="col-sm-1-10 wt-page-options-value pt-2" id="suppimplex" title="<?= I18N::translate('Checked -> Implex-affected relations will not be pursued further') ?>">
            <?php $label_spi = I18N::translate('Suppress Implex'); ?>
            <?=
                view('components/checkbox', [
                'name' => 'suppimplex', 'id' => 'cb_spimplex', 'value' => $suppimplex, 'checked' => ($suppimplex > 0), 'label' => $label_spi ])
            ?>
        </div>
        <div class="col-sm-1-10 wt-page-options-value pt-2" id="markdeceased" title="<?= I18N::translate('Checked -> Deceased will be explicitely marked') ?>">
            <?php $label_md = I18N::translate('Mark Deceased'); ?>
            <?=
                view('components/checkbox', [
                'name' => 'markdeceased', 'id' => 'cb_mdeceased', 'value' => $markdeceased, 'checked' => ($markdeceased > 0), 'label' => $label_md ])
            ?>
        </div>
        <div class="col-sm-1-10 wt-page-options-value pt-2" id="showseparated" title="<?= I18N::translate('Checked -> Multiple relationships are resolved separately') ?>">
            <?php $label_sg = I18N::translate('Show separated'); ?>
            <?=
                view('components/checkbox', [
                'name' => 'showseparated', 'id' => 'cb_mode', 'value' => $showseparated, 'checked' => ($showseparated > 0), 'label' => $label_sg ])
            ?>
        </div>
    </div>
</form>
<?= View::push('javascript') ?>
<script>
  showgensPrep();
</script>
<?= View::endpush() ?>

<?php if ($show_path):
    if (is_array($verData)):           // [EW.H] debug option - show the processed path
        $xtpath = join(' | ', $verData['path']); ?>
        <div> <?= $xtpath ?></div>
    <?php endif ?>
    <?php if (is_array($xtStruct)):           // [EW.H] debug option - show the processed path
        foreach ($xtStruct['parts'] as $n => $part) { 
            $xtpath = join(' | ', $part['path']); ?>
            <div> <?= $xtpath ?></div>
        <?php  } ?>
    <?php endif ?>
<?php endif ?>

<?php for ( $i = 0, $iE = count($htmls); $i < $iE; ++$i) : ?>
    <?php $html = $subtitles[$i] ?>
        <?= $html ?>
    <?php $html = $htmls[$i] ?>
    <div class="wt-page-content wt-chart wt-chart-interactive">
        <?= $html ?>
    </div>
    <?php $js = $jss[$i] ?>
    <?php View::push('javascript') ?>
    <script>
        <?= $js ?>
    </script>
    <?php View::endpush() ?>
<?php endfor ?>
